on:
  workflow_dispatch: {}
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v38.1.6
        with:
          renovate-version: '36.1.11'
          configurationFile: 'renovate-config.js'
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: 'debug'